### ISSUE TITLE
Visualize bonus metrics for ranked classifiers

### ISSUE THREAD

**Issue by aimalz** [aimalz/proclam#81]
@kponder's upgraded version of Figure 5 will remain in the paper, but we also need an additional plot for the probabilistic adaptations of deterministic metrics.  This issue is a place for discussing how best to visualize the additional metrics so #78 can progress independently from the identification of an appropriate plotting scheme.

**Comment by aimalz** [comment]
The referee agrees with us both that the paper has too many tables and that the most useful information is the ranking under each metric, not the absolute values of the metrics.  To visualize the rank changes under each metric, we could turn Tables 1 and 2 and, separately, Table 3 into a pair of new figures in addition to Figure 5 using [a slope graph](https://www.dundas.com/support/blog/identify-rank-changes-in-your-data-using-a-slope-graph) or [parallel coordinates plot](https://medium.com/@EvanSinar/7-data-visualization-types-you-should-be-using-more-and-how-to-start-4015b5d4adf2).
_(Edited for clarity)_

**Comment by kponder** [comment]
Here is the current working concept to visualize [Table 3 (Option 1)](https://github.com/aimalz/proclam/files/3277884/Tables3_option3.pdf). I'm still working on ways to make this plot clearer and suggestions are welcome. The [Table 3 (Option 2)](https://github.com/aimalz/proclam/files/3277896/Tables3_option4.pdf) is one suggestion where we focus the plot on template-based classifiers instead of wavelet-based since the template classifiers tend to perform better than their wavelet counterparts. 

Upon discussion with @aimalz, we decided that Tables 1 and 2 can be removed from the paper and not turned into plots since the numbers can now be read off the updated Figure 5.

[Table3_option1.pdf](https://github.com/aimalz/proclam/files/3277884/Tables3_option3.pdf)
[Table3_option2.pdf](https://github.com/aimalz/proclam/files/3277896/Tables3_option4.pdf)

**Comment by aimalz** [comment]
The paper has now been accepted for publication so we no longer need this issue.  (-:
